version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dungdh7
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
    postgres: